# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeisknowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='fact_name',
            field=models.CharField(max_length=20),
        ),
    ]
