# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeisknowledge', '0002_auto_20171004_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='fact_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fact',
            name='link',
            field=models.CharField(max_length=50),
        ),
    ]
